name: wsindy_for_pdes
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - numpy
  - scipy
  - matplotlib
  - ipython
  - jupyter
  - pip
  - pytorch
  - cpuonly
  - tqdm
  - h5py
  - pip:
    - symengine
